Port nyu_finger to odri_control_interface, enable double finger support, enable PD control on the cards
open-dynamic-robot-initiative/nyu_finger pull request #1
Opened 2021-06-22 18:50 UTC by jviereck

Tested on the real finger setup.

2021-06-23 14:07 UTC, MaximilienNaveau requested changes

2021-06-23 14:07 UTC, MaximilienNaveau commented on CMakeLists.txt
> +    src/nyu_finger.cpp
why do you need to add this files `src/nyu_finger.cpp`? they should be included in the `nyu_finger` library.

2021-06-23 14:07 UTC, MaximilienNaveau commented on demos/nyu_finger_dgh.py
> +yaml_file = '/home/jviereck/dev/dgm_refactoring/workspace/src/robot_properties_nyu_finger/src/robot_properties_nyu_finger/robot_properties_nyu_finger/dynamic_graph_manager/dgm_parameters_nyu_finger_d
Please do not put path like this in files :-1: , this is a security risk for you, better simply do:
```
from pathlib import Path
import  robot_properties_nyu_finger
yaml_file = str(
    Path(pinocchio.__file__).resolve().parent /
    "robot_properties_nyu_finger" /
    "dynamic_graph_manager" /
    "dgm_parameters_nyu_finger_double_0.yaml"
)
```

2021-06-23 14:07 UTC, MaximilienNaveau commented on demos/nyu_finger_dgh.py
> +yaml_file = '/home/jviereck/dev/dgm_refactoring/workspace/src/robot_properties_nyu_finger/src/robot_properties_nyu_finger/robot_properties_nyu_finger/dynamic_graph_manager/dgm_parameters_nyu_finger_d
idem than above

2021-06-23 14:07 UTC, MaximilienNaveau commented on demos/nyu_finger_double_dgh.py
> +yaml_file = '/home/jviereck/dev/dgm_refactoring/workspace/src/robot_properties_nyu_finger/src/robot_properties_nyu_finger/robot_properties_nyu_finger/dynamic_graph_manager/dgm_parameters_nyu_finger_d
idem no full path

2021-06-23 14:07 UTC, MaximilienNaveau commented on demos/nyu_finger_double_dgh.py
> +yaml_file = '/home/jviereck/dev/dgm_refactoring/workspace/src/robot_properties_nyu_finger/src/robot_properties_nyu_finger/robot_properties_nyu_finger/dynamic_graph_manager/dgm_parameters_nyu_finger_d
idem no full path!

2021-06-23 14:07 UTC, MaximilienNaveau commented on demos/nyu_finger_double_hwp.py
> +    yaml_path = '/home/jviereck/dev/dgm_refactoring/workspace/install/robot_properties_nyu_finger/lib/python3.6/site-packages/robot_properties_nyu_finger/robot_properties_nyu_finger/dynamic_graph_man
idem no full path!

2021-06-23 14:07 UTC, MaximilienNaveau commented on demos/nyu_finger_double_pd_dgh.py
> +yaml_file = '/home/jviereck/dev/dgm_refactoring/workspace/src/robot_properties_nyu_finger/src/robot_properties_nyu_finger/robot_properties_nyu_finger/dynamic_graph_manager/dgm_parameters_nyu_finger_d
idem

2021-06-23 14:07 UTC, MaximilienNaveau commented on demos/nyu_finger_double_pd_dgh.py
> +yaml_file = '/home/jviereck/dev/dgm_refactoring/workspace/src/robot_properties_nyu_finger/src/robot_properties_nyu_finger/robot_properties_nyu_finger/dynamic_graph_manager/dgm_parameters_nyu_finger_d
idem

2021-06-23 14:07 UTC, MaximilienNaveau commented on include/nyu_finger/dynamic_graph_manager/dgm_nyu_finger.hpp
> +// #include "dynamic_graph_manager/dynamic_graph_manager.hpp"
remove line

2021-06-23 14:07 UTC, MaximilienNaveau commented on include/nyu_finger/dynamic_graph_manager/dgm_nyu_finger.hpp
> +    void initialize_drivers();
set it as virtual to indicate you inherited it. Or specify it in the doc string.

2021-06-23 14:07 UTC, MaximilienNaveau commented on package.xml
>    <depend>master_board_sdk_catkin</depend>
old stuff to be renamed

2021-06-23 14:07 UTC, MaximilienNaveau commented on src/CMakeLists.txt
> +  # build_dgm_programs(nyu_finger_double)
why not building the nyu_finger_double above?
otherwise please remove the comment or add a @todo

2021-06-23 14:07 UTC, MaximilienNaveau commented on src/dynamic_graph_manager/dg_main_nyu_finger.cpp
> + * \brief Execute the main program to control the solo
wrong header docstring, please check all

2021-06-23 14:07 UTC, MaximilienNaveau commented on src/dynamic_graph_manager/dgm_nyu_finger.cpp
> +        auto ctrl_joint_positions = map.at("ctrl_joint_positions");
Try to avoid auto here as you do not control the memory allocation. This is not a good practice for real-time application.
You should create attributes of this class a pre-allocate the size.
And potentially do an assert on the size that is return from the SharedMemory

2021-06-23 14:07 UTC, MaximilienNaveau commented on src/dynamic_graph_manager/dgm_nyu_finger.cpp
> +void DGMNYUFinger::calibrate_joint_position(
here I created another function for solo I think:
```
DGMNYUFinger::calibrate_joint_position();
```
This way I assume the code already knows the offsets from the yaml file

2021-06-23 14:07 UTC, MaximilienNaveau commented on src/nyu_finger.cpp
> +	    motor_board_enabled_[i] = false;
weird indent

2021-06-23 14:07 UTC, MaximilienNaveau commented on src/nyu_finger.cpp
> +    VectorXi motor_numbers_(3);
Do not declare a variable that is local with a trailing underscore. This cause nasty bugs before, and can cause more in the future.

2021-06-23 17:17 UTC, jviereck commented on CMakeLists.txt
> +    src/nyu_finger.cpp
Good catch - removed the file dependency.

2021-06-23 17:30 UTC, jviereck commented on demos/nyu_finger_dgh.py
> +yaml_file = '/home/jviereck/dev/dgm_refactoring/workspace/src/robot_properties_nyu_finger/src/robot_properties_nyu_finger/robot_properties_nyu_finger/dynamic_graph_manager/dgm_parameters_nyu_finger_d
Fixed. By now we can use the `robot_properties_nyu_finger` and then do nicely:

```
from robot_properties_nyu_finger.config import NYUFingerConfig

yaml_file = os.path.join(NYUFingerConfig.dgm_yaml_dir, 'dgm_parameters_nyu_finger.yaml')
```

2021-06-23 17:31 UTC, jviereck commented on demos/nyu_finger_double_dgh.py
> +yaml_file = '/home/jviereck/dev/dgm_refactoring/workspace/src/robot_properties_nyu_finger/src/robot_properties_nyu_finger/robot_properties_nyu_finger/dynamic_graph_manager/dgm_parameters_nyu_finger_d
Same fix as above.

2021-06-23 17:34 UTC, jviereck commented on demos/nyu_finger_double_dgh.py
> +yaml_file = '/home/jviereck/dev/dgm_refactoring/workspace/src/robot_properties_nyu_finger/src/robot_properties_nyu_finger/robot_properties_nyu_finger/dynamic_graph_manager/dgm_parameters_nyu_finger_d
Same fix as above.

2021-06-23 17:34 UTC, jviereck commented on demos/nyu_finger_double_hwp.py
> +    yaml_path = '/home/jviereck/dev/dgm_refactoring/workspace/install/robot_properties_nyu_finger/lib/python3.6/site-packages/robot_properties_nyu_finger/robot_properties_nyu_finger/dynamic_graph_man
Same fix as above.

2021-06-23 17:35 UTC, jviereck commented on demos/nyu_finger_double_pd_dgh.py
> +yaml_file = '/home/jviereck/dev/dgm_refactoring/workspace/src/robot_properties_nyu_finger/src/robot_properties_nyu_finger/robot_properties_nyu_finger/dynamic_graph_manager/dgm_parameters_nyu_finger_d
Same fix as above.

2021-06-23 17:36 UTC, jviereck commented on include/nyu_finger/dynamic_graph_manager/dgm_nyu_finger.hpp
> +    void initialize_drivers();
Added virtual keyword.

2021-06-23 17:37 UTC, jviereck commented on package.xml
>    <depend>master_board_sdk_catkin</depend>
What do you mean by renamed here? The two lines got removed in this PR?

2021-06-23 17:38 UTC, jviereck commented on src/CMakeLists.txt
> +  # build_dgm_programs(nyu_finger_double)
At this point there is no `dgm_nyu_finger_double` anymore. Instead we spawn the same `dgm_nyu_finger` twice.

Removed the line.

2021-06-23 17:53 UTC, jviereck commented on src/dynamic_graph_manager/dgm_nyu_finger.cpp
> +        auto ctrl_joint_positions = map.at("ctrl_joint_positions");
I didn't know that `auto` was causing memory issues. I've created attributes on the class now.

2021-06-23 17:54 UTC, jviereck commented on src/dynamic_graph_manager/dgm_nyu_finger.cpp
> +void DGMNYUFinger::calibrate_joint_position(
Good point! I've created `calibrate_joint_position_from_yaml`.

2021-06-23 17:57 UTC, jviereck commented on src/nyu_finger.cpp
> +	    motor_board_enabled_[i] = false;
Strange, this looks fixed for me...

2021-06-23 17:58 UTC, jviereck commented on src/nyu_finger.cpp
> +    VectorXi motor_numbers_(3);
Good point, I changed it to `motor_numbers_int`.

2021-06-23 18:05 UTC, jviereck commented
I should have addressed all changed. Please have another look @MaximilienNaveau and once you give you approval I will merge it.

2021-06-23 20:40 UTC, MaximilienNaveau commented on package.xml
>    <depend>master_board_sdk_catkin</depend>
Remove the catkin

2021-06-23 20:42 UTC, MaximilienNaveau commented on src/nyu_finger.cpp
> +	    motor_board_enabled_[i] = false;
Use spaces?

2021-06-23 20:43 UTC, MaximilienNaveau requested changes
Still some minor changes

2021-06-23 20:46 UTC, jviereck commented on package.xml
>    <depend>master_board_sdk_catkin</depend>
Do we need the `package.xml` at all these days?

2021-06-23 20:48 UTC, jviereck commented on package.xml
>    <depend>master_board_sdk_catkin</depend>
I've updated the `buildtool_depend` as follows;

```
  <buildtool_depend>cmake</buildtool_depend>
  <buildtool_depend>pybind11_vendor</buildtool_depend>
  <buildtool_depend>mpi_cmake_modules</buildtool_depend>
  ```

2021-06-23 20:49 UTC, jviereck commented on package.xml
>    <depend>master_board_sdk_catkin</depend>
Is this correct?

2021-06-23 20:54 UTC, jviereck commented on src/nyu_finger.cpp
> +	    motor_board_enabled_[i] = false;
Right, now I see it. Fixed!

2021-06-24 00:57 UTC, jviereck commented
I am merging this one as I have someone from Stuttgart waiting for the code and I don't want them to wait longer. If there is anything else that needs changing I will make a followup PR.

2021-06-24 00:57 UTC, merged